### ISSUE TITLE
ESLint v9 flat config

### ISSUE THREAD

**Issue by mike-lock** [szhsin/eslint-plugin-react-hooks-addons#116]
Hello,

Is the support of ESLint v9 + flat config going to be supported in the near future?

Greetings,

Mike

**Comment by szhsin** [comment]
Hey @mike-lock , 

Supporting flat config has actually been planned!

Meanwhile, you could use the `@eslint/compat` to adapt the legacy config for now [like this one](https://github.com/szhsin/react-accordion/blob/da37ff6b92192f3356a6958bde54c7aff1a8d64f/eslint.config.mjs#L59).

**Comment by szhsin** [comment]
Added support for the [flat config](https://github.com/szhsin/eslint-plugin-react-hooks-addons?tab=readme-ov-file#flat-config) in [v0.4.0](https://github.com/szhsin/eslint-plugin-react-hooks-addons/releases/tag/v0.4.0).
